// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: proto_rosbag2.proto

#ifndef PROTOBUF_INCLUDED_proto_5frosbag2_2eproto
#define PROTOBUF_INCLUDED_proto_5frosbag2_2eproto

#include <string>

#include <google/protobuf/stubs/common.h>

#if GOOGLE_PROTOBUF_VERSION < 3006001
#error This file was generated by a newer version of protoc which is
#error incompatible with your Protocol Buffer headers.  Please update
#error your headers.
#endif
#if 3006001 < GOOGLE_PROTOBUF_MIN_PROTOC_VERSION
#error This file was generated by an older version of protoc which is
#error incompatible with your Protocol Buffer headers.  Please
#error regenerate this file with a newer version of protoc.
#endif

#include <google/protobuf/io/coded_stream.h>
#include <google/protobuf/arena.h>
#include <google/protobuf/arenastring.h>
#include <google/protobuf/generated_message_table_driven.h>
#include <google/protobuf/generated_message_util.h>
#include <google/protobuf/inlined_string_field.h>
#include <google/protobuf/metadata.h>
#include <google/protobuf/message.h>
#include <google/protobuf/repeated_field.h>  // IWYU pragma: export
#include <google/protobuf/extension_set.h>  // IWYU pragma: export
#include <google/protobuf/unknown_field_set.h>
// @@protoc_insertion_point(includes)
#define PROTOBUF_INTERNAL_EXPORT_protobuf_proto_5frosbag2_2eproto 

namespace protobuf_proto_5frosbag2_2eproto {
// Internal implementation detail -- do not use these members.
struct TableStruct {
  static const ::google::protobuf::internal::ParseTableField entries[];
  static const ::google::protobuf::internal::AuxillaryParseTableField aux[];
  static const ::google::protobuf::internal::ParseTable schema[2];
  static const ::google::protobuf::internal::FieldMetadata field_metadata[];
  static const ::google::protobuf::internal::SerializationTable serialization_table[];
  static const ::google::protobuf::uint32 offsets[];
};
void AddDescriptors();
}  // namespace protobuf_proto_5frosbag2_2eproto
namespace rosbag_converter_proto {
class ProtoRosBag2;
class ProtoRosBag2DefaultTypeInternal;
extern ProtoRosBag2DefaultTypeInternal _ProtoRosBag2_default_instance_;
class ProtoRosBag2_ProtoRosBag2Message;
class ProtoRosBag2_ProtoRosBag2MessageDefaultTypeInternal;
extern ProtoRosBag2_ProtoRosBag2MessageDefaultTypeInternal _ProtoRosBag2_ProtoRosBag2Message_default_instance_;
}  // namespace rosbag_converter_proto
namespace google {
namespace protobuf {
template<> ::rosbag_converter_proto::ProtoRosBag2* Arena::CreateMaybeMessage<::rosbag_converter_proto::ProtoRosBag2>(Arena*);
template<> ::rosbag_converter_proto::ProtoRosBag2_ProtoRosBag2Message* Arena::CreateMaybeMessage<::rosbag_converter_proto::ProtoRosBag2_ProtoRosBag2Message>(Arena*);
}  // namespace protobuf
}  // namespace google
namespace rosbag_converter_proto {

// ===================================================================

class ProtoRosBag2_ProtoRosBag2Message : public ::google::protobuf::Message /* @@protoc_insertion_point(class_definition:rosbag_converter_proto.ProtoRosBag2.ProtoRosBag2Message) */ {
 public:
  ProtoRosBag2_ProtoRosBag2Message();
  virtual ~ProtoRosBag2_ProtoRosBag2Message();

  ProtoRosBag2_ProtoRosBag2Message(const ProtoRosBag2_ProtoRosBag2Message& from);

  inline ProtoRosBag2_ProtoRosBag2Message& operator=(const ProtoRosBag2_ProtoRosBag2Message& from) {
    CopyFrom(from);
    return *this;
  }
  #if LANG_CXX11
  ProtoRosBag2_ProtoRosBag2Message(ProtoRosBag2_ProtoRosBag2Message&& from) noexcept
    : ProtoRosBag2_ProtoRosBag2Message() {
    *this = ::std::move(from);
  }

  inline ProtoRosBag2_ProtoRosBag2Message& operator=(ProtoRosBag2_ProtoRosBag2Message&& from) noexcept {
    if (GetArenaNoVirtual() == from.GetArenaNoVirtual()) {
      if (this != &from) InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }
  #endif
  static const ::google::protobuf::Descriptor* descriptor();
  static const ProtoRosBag2_ProtoRosBag2Message& default_instance();

  static void InitAsDefaultInstance();  // FOR INTERNAL USE ONLY
  static inline const ProtoRosBag2_ProtoRosBag2Message* internal_default_instance() {
    return reinterpret_cast<const ProtoRosBag2_ProtoRosBag2Message*>(
               &_ProtoRosBag2_ProtoRosBag2Message_default_instance_);
  }
  static constexpr int kIndexInFileMessages =
    0;

  void Swap(ProtoRosBag2_ProtoRosBag2Message* other);
  friend void swap(ProtoRosBag2_ProtoRosBag2Message& a, ProtoRosBag2_ProtoRosBag2Message& b) {
    a.Swap(&b);
  }

  // implements Message ----------------------------------------------

  inline ProtoRosBag2_ProtoRosBag2Message* New() const final {
    return CreateMaybeMessage<ProtoRosBag2_ProtoRosBag2Message>(NULL);
  }

  ProtoRosBag2_ProtoRosBag2Message* New(::google::protobuf::Arena* arena) const final {
    return CreateMaybeMessage<ProtoRosBag2_ProtoRosBag2Message>(arena);
  }
  void CopyFrom(const ::google::protobuf::Message& from) final;
  void MergeFrom(const ::google::protobuf::Message& from) final;
  void CopyFrom(const ProtoRosBag2_ProtoRosBag2Message& from);
  void MergeFrom(const ProtoRosBag2_ProtoRosBag2Message& from);
  void Clear() final;
  bool IsInitialized() const final;

  size_t ByteSizeLong() const final;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input) final;
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const final;
  ::google::protobuf::uint8* InternalSerializeWithCachedSizesToArray(
      bool deterministic, ::google::protobuf::uint8* target) const final;
  int GetCachedSize() const final { return _cached_size_.Get(); }

  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const final;
  void InternalSwap(ProtoRosBag2_ProtoRosBag2Message* other);
  private:
  inline ::google::protobuf::Arena* GetArenaNoVirtual() const {
    return NULL;
  }
  inline void* MaybeArenaPtr() const {
    return NULL;
  }
  public:

  ::google::protobuf::Metadata GetMetadata() const final;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  // string topic_name = 1;
  void clear_topic_name();
  static const int kTopicNameFieldNumber = 1;
  const ::std::string& topic_name() const;
  void set_topic_name(const ::std::string& value);
  #if LANG_CXX11
  void set_topic_name(::std::string&& value);
  #endif
  void set_topic_name(const char* value);
  void set_topic_name(const char* value, size_t size);
  ::std::string* mutable_topic_name();
  ::std::string* release_topic_name();
  void set_allocated_topic_name(::std::string* topic_name);

  // string topic_type_name = 2;
  void clear_topic_type_name();
  static const int kTopicTypeNameFieldNumber = 2;
  const ::std::string& topic_type_name() const;
  void set_topic_type_name(const ::std::string& value);
  #if LANG_CXX11
  void set_topic_type_name(::std::string&& value);
  #endif
  void set_topic_type_name(const char* value);
  void set_topic_type_name(const char* value, size_t size);
  ::std::string* mutable_topic_type_name();
  ::std::string* release_topic_type_name();
  void set_allocated_topic_type_name(::std::string* topic_type_name);

  // bytes serialized_data = 4;
  void clear_serialized_data();
  static const int kSerializedDataFieldNumber = 4;
  const ::std::string& serialized_data() const;
  void set_serialized_data(const ::std::string& value);
  #if LANG_CXX11
  void set_serialized_data(::std::string&& value);
  #endif
  void set_serialized_data(const char* value);
  void set_serialized_data(const void* value, size_t size);
  ::std::string* mutable_serialized_data();
  ::std::string* release_serialized_data();
  void set_allocated_serialized_data(::std::string* serialized_data);

  // uint64 time_stamp = 3;
  void clear_time_stamp();
  static const int kTimeStampFieldNumber = 3;
  ::google::protobuf::uint64 time_stamp() const;
  void set_time_stamp(::google::protobuf::uint64 value);

  // @@protoc_insertion_point(class_scope:rosbag_converter_proto.ProtoRosBag2.ProtoRosBag2Message)
 private:

  ::google::protobuf::internal::InternalMetadataWithArena _internal_metadata_;
  ::google::protobuf::internal::ArenaStringPtr topic_name_;
  ::google::protobuf::internal::ArenaStringPtr topic_type_name_;
  ::google::protobuf::internal::ArenaStringPtr serialized_data_;
  ::google::protobuf::uint64 time_stamp_;
  mutable ::google::protobuf::internal::CachedSize _cached_size_;
  friend struct ::protobuf_proto_5frosbag2_2eproto::TableStruct;
};
// -------------------------------------------------------------------

class ProtoRosBag2 : public ::google::protobuf::Message /* @@protoc_insertion_point(class_definition:rosbag_converter_proto.ProtoRosBag2) */ {
 public:
  ProtoRosBag2();
  virtual ~ProtoRosBag2();

  ProtoRosBag2(const ProtoRosBag2& from);

  inline ProtoRosBag2& operator=(const ProtoRosBag2& from) {
    CopyFrom(from);
    return *this;
  }
  #if LANG_CXX11
  ProtoRosBag2(ProtoRosBag2&& from) noexcept
    : ProtoRosBag2() {
    *this = ::std::move(from);
  }

  inline ProtoRosBag2& operator=(ProtoRosBag2&& from) noexcept {
    if (GetArenaNoVirtual() == from.GetArenaNoVirtual()) {
      if (this != &from) InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }
  #endif
  static const ::google::protobuf::Descriptor* descriptor();
  static const ProtoRosBag2& default_instance();

  static void InitAsDefaultInstance();  // FOR INTERNAL USE ONLY
  static inline const ProtoRosBag2* internal_default_instance() {
    return reinterpret_cast<const ProtoRosBag2*>(
               &_ProtoRosBag2_default_instance_);
  }
  static constexpr int kIndexInFileMessages =
    1;

  void Swap(ProtoRosBag2* other);
  friend void swap(ProtoRosBag2& a, ProtoRosBag2& b) {
    a.Swap(&b);
  }

  // implements Message ----------------------------------------------

  inline ProtoRosBag2* New() const final {
    return CreateMaybeMessage<ProtoRosBag2>(NULL);
  }

  ProtoRosBag2* New(::google::protobuf::Arena* arena) const final {
    return CreateMaybeMessage<ProtoRosBag2>(arena);
  }
  void CopyFrom(const ::google::protobuf::Message& from) final;
  void MergeFrom(const ::google::protobuf::Message& from) final;
  void CopyFrom(const ProtoRosBag2& from);
  void MergeFrom(const ProtoRosBag2& from);
  void Clear() final;
  bool IsInitialized() const final;

  size_t ByteSizeLong() const final;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input) final;
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const final;
  ::google::protobuf::uint8* InternalSerializeWithCachedSizesToArray(
      bool deterministic, ::google::protobuf::uint8* target) const final;
  int GetCachedSize() const final { return _cached_size_.Get(); }

  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const final;
  void InternalSwap(ProtoRosBag2* other);
  private:
  inline ::google::protobuf::Arena* GetArenaNoVirtual() const {
    return NULL;
  }
  inline void* MaybeArenaPtr() const {
    return NULL;
  }
  public:

  ::google::protobuf::Metadata GetMetadata() const final;

  // nested types ----------------------------------------------------

  typedef ProtoRosBag2_ProtoRosBag2Message ProtoRosBag2Message;

  // accessors -------------------------------------------------------

  // repeated .rosbag_converter_proto.ProtoRosBag2.ProtoRosBag2Message messages = 1;
  int messages_size() const;
  void clear_messages();
  static const int kMessagesFieldNumber = 1;
  ::rosbag_converter_proto::ProtoRosBag2_ProtoRosBag2Message* mutable_messages(int index);
  ::google::protobuf::RepeatedPtrField< ::rosbag_converter_proto::ProtoRosBag2_ProtoRosBag2Message >*
      mutable_messages();
  const ::rosbag_converter_proto::ProtoRosBag2_ProtoRosBag2Message& messages(int index) const;
  ::rosbag_converter_proto::ProtoRosBag2_ProtoRosBag2Message* add_messages();
  const ::google::protobuf::RepeatedPtrField< ::rosbag_converter_proto::ProtoRosBag2_ProtoRosBag2Message >&
      messages() const;

  // @@protoc_insertion_point(class_scope:rosbag_converter_proto.ProtoRosBag2)
 private:

  ::google::protobuf::internal::InternalMetadataWithArena _internal_metadata_;
  ::google::protobuf::RepeatedPtrField< ::rosbag_converter_proto::ProtoRosBag2_ProtoRosBag2Message > messages_;
  mutable ::google::protobuf::internal::CachedSize _cached_size_;
  friend struct ::protobuf_proto_5frosbag2_2eproto::TableStruct;
};
// ===================================================================


// ===================================================================

#ifdef __GNUC__
  #pragma GCC diagnostic push
  #pragma GCC diagnostic ignored "-Wstrict-aliasing"
#endif  // __GNUC__
// ProtoRosBag2_ProtoRosBag2Message

// string topic_name = 1;
inline void ProtoRosBag2_ProtoRosBag2Message::clear_topic_name() {
  topic_name_.ClearToEmptyNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline const ::std::string& ProtoRosBag2_ProtoRosBag2Message::topic_name() const {
  // @@protoc_insertion_point(field_get:rosbag_converter_proto.ProtoRosBag2.ProtoRosBag2Message.topic_name)
  return topic_name_.GetNoArena();
}
inline void ProtoRosBag2_ProtoRosBag2Message::set_topic_name(const ::std::string& value) {
  
  topic_name_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), value);
  // @@protoc_insertion_point(field_set:rosbag_converter_proto.ProtoRosBag2.ProtoRosBag2Message.topic_name)
}
#if LANG_CXX11
inline void ProtoRosBag2_ProtoRosBag2Message::set_topic_name(::std::string&& value) {
  
  topic_name_.SetNoArena(
    &::google::protobuf::internal::GetEmptyStringAlreadyInited(), ::std::move(value));
  // @@protoc_insertion_point(field_set_rvalue:rosbag_converter_proto.ProtoRosBag2.ProtoRosBag2Message.topic_name)
}
#endif
inline void ProtoRosBag2_ProtoRosBag2Message::set_topic_name(const char* value) {
  GOOGLE_DCHECK(value != NULL);
  
  topic_name_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), ::std::string(value));
  // @@protoc_insertion_point(field_set_char:rosbag_converter_proto.ProtoRosBag2.ProtoRosBag2Message.topic_name)
}
inline void ProtoRosBag2_ProtoRosBag2Message::set_topic_name(const char* value, size_t size) {
  
  topic_name_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(),
      ::std::string(reinterpret_cast<const char*>(value), size));
  // @@protoc_insertion_point(field_set_pointer:rosbag_converter_proto.ProtoRosBag2.ProtoRosBag2Message.topic_name)
}
inline ::std::string* ProtoRosBag2_ProtoRosBag2Message::mutable_topic_name() {
  
  // @@protoc_insertion_point(field_mutable:rosbag_converter_proto.ProtoRosBag2.ProtoRosBag2Message.topic_name)
  return topic_name_.MutableNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline ::std::string* ProtoRosBag2_ProtoRosBag2Message::release_topic_name() {
  // @@protoc_insertion_point(field_release:rosbag_converter_proto.ProtoRosBag2.ProtoRosBag2Message.topic_name)
  
  return topic_name_.ReleaseNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline void ProtoRosBag2_ProtoRosBag2Message::set_allocated_topic_name(::std::string* topic_name) {
  if (topic_name != NULL) {
    
  } else {
    
  }
  topic_name_.SetAllocatedNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), topic_name);
  // @@protoc_insertion_point(field_set_allocated:rosbag_converter_proto.ProtoRosBag2.ProtoRosBag2Message.topic_name)
}

// string topic_type_name = 2;
inline void ProtoRosBag2_ProtoRosBag2Message::clear_topic_type_name() {
  topic_type_name_.ClearToEmptyNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline const ::std::string& ProtoRosBag2_ProtoRosBag2Message::topic_type_name() const {
  // @@protoc_insertion_point(field_get:rosbag_converter_proto.ProtoRosBag2.ProtoRosBag2Message.topic_type_name)
  return topic_type_name_.GetNoArena();
}
inline void ProtoRosBag2_ProtoRosBag2Message::set_topic_type_name(const ::std::string& value) {
  
  topic_type_name_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), value);
  // @@protoc_insertion_point(field_set:rosbag_converter_proto.ProtoRosBag2.ProtoRosBag2Message.topic_type_name)
}
#if LANG_CXX11
inline void ProtoRosBag2_ProtoRosBag2Message::set_topic_type_name(::std::string&& value) {
  
  topic_type_name_.SetNoArena(
    &::google::protobuf::internal::GetEmptyStringAlreadyInited(), ::std::move(value));
  // @@protoc_insertion_point(field_set_rvalue:rosbag_converter_proto.ProtoRosBag2.ProtoRosBag2Message.topic_type_name)
}
#endif
inline void ProtoRosBag2_ProtoRosBag2Message::set_topic_type_name(const char* value) {
  GOOGLE_DCHECK(value != NULL);
  
  topic_type_name_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), ::std::string(value));
  // @@protoc_insertion_point(field_set_char:rosbag_converter_proto.ProtoRosBag2.ProtoRosBag2Message.topic_type_name)
}
inline void ProtoRosBag2_ProtoRosBag2Message::set_topic_type_name(const char* value, size_t size) {
  
  topic_type_name_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(),
      ::std::string(reinterpret_cast<const char*>(value), size));
  // @@protoc_insertion_point(field_set_pointer:rosbag_converter_proto.ProtoRosBag2.ProtoRosBag2Message.topic_type_name)
}
inline ::std::string* ProtoRosBag2_ProtoRosBag2Message::mutable_topic_type_name() {
  
  // @@protoc_insertion_point(field_mutable:rosbag_converter_proto.ProtoRosBag2.ProtoRosBag2Message.topic_type_name)
  return topic_type_name_.MutableNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline ::std::string* ProtoRosBag2_ProtoRosBag2Message::release_topic_type_name() {
  // @@protoc_insertion_point(field_release:rosbag_converter_proto.ProtoRosBag2.ProtoRosBag2Message.topic_type_name)
  
  return topic_type_name_.ReleaseNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline void ProtoRosBag2_ProtoRosBag2Message::set_allocated_topic_type_name(::std::string* topic_type_name) {
  if (topic_type_name != NULL) {
    
  } else {
    
  }
  topic_type_name_.SetAllocatedNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), topic_type_name);
  // @@protoc_insertion_point(field_set_allocated:rosbag_converter_proto.ProtoRosBag2.ProtoRosBag2Message.topic_type_name)
}

// uint64 time_stamp = 3;
inline void ProtoRosBag2_ProtoRosBag2Message::clear_time_stamp() {
  time_stamp_ = GOOGLE_ULONGLONG(0);
}
inline ::google::protobuf::uint64 ProtoRosBag2_ProtoRosBag2Message::time_stamp() const {
  // @@protoc_insertion_point(field_get:rosbag_converter_proto.ProtoRosBag2.ProtoRosBag2Message.time_stamp)
  return time_stamp_;
}
inline void ProtoRosBag2_ProtoRosBag2Message::set_time_stamp(::google::protobuf::uint64 value) {
  
  time_stamp_ = value;
  // @@protoc_insertion_point(field_set:rosbag_converter_proto.ProtoRosBag2.ProtoRosBag2Message.time_stamp)
}

// bytes serialized_data = 4;
inline void ProtoRosBag2_ProtoRosBag2Message::clear_serialized_data() {
  serialized_data_.ClearToEmptyNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline const ::std::string& ProtoRosBag2_ProtoRosBag2Message::serialized_data() const {
  // @@protoc_insertion_point(field_get:rosbag_converter_proto.ProtoRosBag2.ProtoRosBag2Message.serialized_data)
  return serialized_data_.GetNoArena();
}
inline void ProtoRosBag2_ProtoRosBag2Message::set_serialized_data(const ::std::string& value) {
  
  serialized_data_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), value);
  // @@protoc_insertion_point(field_set:rosbag_converter_proto.ProtoRosBag2.ProtoRosBag2Message.serialized_data)
}
#if LANG_CXX11
inline void ProtoRosBag2_ProtoRosBag2Message::set_serialized_data(::std::string&& value) {
  
  serialized_data_.SetNoArena(
    &::google::protobuf::internal::GetEmptyStringAlreadyInited(), ::std::move(value));
  // @@protoc_insertion_point(field_set_rvalue:rosbag_converter_proto.ProtoRosBag2.ProtoRosBag2Message.serialized_data)
}
#endif
inline void ProtoRosBag2_ProtoRosBag2Message::set_serialized_data(const char* value) {
  GOOGLE_DCHECK(value != NULL);
  
  serialized_data_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), ::std::string(value));
  // @@protoc_insertion_point(field_set_char:rosbag_converter_proto.ProtoRosBag2.ProtoRosBag2Message.serialized_data)
}
inline void ProtoRosBag2_ProtoRosBag2Message::set_serialized_data(const void* value, size_t size) {
  
  serialized_data_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(),
      ::std::string(reinterpret_cast<const char*>(value), size));
  // @@protoc_insertion_point(field_set_pointer:rosbag_converter_proto.ProtoRosBag2.ProtoRosBag2Message.serialized_data)
}
inline ::std::string* ProtoRosBag2_ProtoRosBag2Message::mutable_serialized_data() {
  
  // @@protoc_insertion_point(field_mutable:rosbag_converter_proto.ProtoRosBag2.ProtoRosBag2Message.serialized_data)
  return serialized_data_.MutableNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline ::std::string* ProtoRosBag2_ProtoRosBag2Message::release_serialized_data() {
  // @@protoc_insertion_point(field_release:rosbag_converter_proto.ProtoRosBag2.ProtoRosBag2Message.serialized_data)
  
  return serialized_data_.ReleaseNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline void ProtoRosBag2_ProtoRosBag2Message::set_allocated_serialized_data(::std::string* serialized_data) {
  if (serialized_data != NULL) {
    
  } else {
    
  }
  serialized_data_.SetAllocatedNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), serialized_data);
  // @@protoc_insertion_point(field_set_allocated:rosbag_converter_proto.ProtoRosBag2.ProtoRosBag2Message.serialized_data)
}

// -------------------------------------------------------------------

// ProtoRosBag2

// repeated .rosbag_converter_proto.ProtoRosBag2.ProtoRosBag2Message messages = 1;
inline int ProtoRosBag2::messages_size() const {
  return messages_.size();
}
inline void ProtoRosBag2::clear_messages() {
  messages_.Clear();
}
inline ::rosbag_converter_proto::ProtoRosBag2_ProtoRosBag2Message* ProtoRosBag2::mutable_messages(int index) {
  // @@protoc_insertion_point(field_mutable:rosbag_converter_proto.ProtoRosBag2.messages)
  return messages_.Mutable(index);
}
inline ::google::protobuf::RepeatedPtrField< ::rosbag_converter_proto::ProtoRosBag2_ProtoRosBag2Message >*
ProtoRosBag2::mutable_messages() {
  // @@protoc_insertion_point(field_mutable_list:rosbag_converter_proto.ProtoRosBag2.messages)
  return &messages_;
}
inline const ::rosbag_converter_proto::ProtoRosBag2_ProtoRosBag2Message& ProtoRosBag2::messages(int index) const {
  // @@protoc_insertion_point(field_get:rosbag_converter_proto.ProtoRosBag2.messages)
  return messages_.Get(index);
}
inline ::rosbag_converter_proto::ProtoRosBag2_ProtoRosBag2Message* ProtoRosBag2::add_messages() {
  // @@protoc_insertion_point(field_add:rosbag_converter_proto.ProtoRosBag2.messages)
  return messages_.Add();
}
inline const ::google::protobuf::RepeatedPtrField< ::rosbag_converter_proto::ProtoRosBag2_ProtoRosBag2Message >&
ProtoRosBag2::messages() const {
  // @@protoc_insertion_point(field_list:rosbag_converter_proto.ProtoRosBag2.messages)
  return messages_;
}

#ifdef __GNUC__
  #pragma GCC diagnostic pop
#endif  // __GNUC__
// -------------------------------------------------------------------


// @@protoc_insertion_point(namespace_scope)

}  // namespace rosbag_converter_proto

// @@protoc_insertion_point(global_scope)

#endif  // PROTOBUF_INCLUDED_proto_5frosbag2_2eproto
